server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: zuul-proxy
  http:
    encoding:
      force-response: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    connect-timeout-millis: 200000
    socket-timeout-millis:  200000

  routes:
    demo:
      path: /demo/**
      serviceId: demo
  strip-prefix: true
  add-host-header: true

ribbon:
  ReadTimeout: 150000


hystrix:
    command:
    default:
      execution:
       isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 200000